name: Bug report
description: Something is broken or behaving incorrectly
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Plugin (OpenCode integration)
        - Memory store (LanceDB / embeddings)
        - Website (codexfi.com)
        - Benchmark
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or output
      render: shell
